// <auto-generated />
using System;
using AqarCare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AqarCare.Migrations
{
    [DbContext(typeof(AqarCareDbContext))]
    [Migration("20260719061738_ProfessionalPackageNames")]
    partial class ProfessionalPackageNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AqarCare.Data.Entities.FinishingPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PricePerSqm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("SupervisionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("FinishingPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "أعدت هذه الباقة لتمكنك من الحصول على أفكار تصميمية إبداعية ( لفيلتك / قصرك / شقتك / مشروعك ) تعد خصيصا على أحدث برامج التصميم ثلاثى الأبعاد وتسلم اليك كألبوم مصور تسطيع من خلاله رؤية حلمك الذى تتطلع الية فى مسكنك أو مشروعك كما سوف ينفذ على أرض الواقع.",
                            IsActive = true,
                            Name = "الاساسية",
                            PricePerSqm = 1800m,
                            ShortDescription = "باقة تشطيب أساسية بجودة موثوقة وأسعار مناسبة",
                            Slug = "essential",
                            SortOrder = 1,
                            SupervisionPercent = 17.5m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "باقة تشطيب توفر مستوى أعلى من خامات التشطيب والتشطيبات مع نفس نظام الدفع والإشراف.",
                            IsActive = true,
                            Name = "برونز",
                            PricePerSqm = 2500m,
                            ShortDescription = "خامات محسّنة وتشطيب متين بمستوى برونزي",
                            Slug = "standard",
                            SortOrder = 2,
                            SupervisionPercent = 17.5m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "باقة تشطيب للعملاء الذين يبحثون عن مستوى فاخر في التشطيبات والديكور.",
                            IsActive = true,
                            Name = "سلفر",
                            PricePerSqm = 3500m,
                            ShortDescription = "خامات فضية متميزة وتشطيبات بمستوى راقٍ",
                            Slug = "premium",
                            SortOrder = 3,
                            SupervisionPercent = 17.5m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "باقة تشطيب بمواد وتشطيبات عالية الجودة.",
                            IsActive = true,
                            Name = "جولد",
                            PricePerSqm = 4500m,
                            ShortDescription = "تشطيب ذهبي بأعلى معايير الجودة والأناقة",
                            Slug = "luxury",
                            SortOrder = 4,
                            SupervisionPercent = 17.5m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "باقة تشطيب شاملة التوريدات بأعلى مستويات الجودة.",
                            IsActive = true,
                            Name = "بلاتينيوم",
                            PricePerSqm = 7000m,
                            ShortDescription = "باقة شاملة التوريدات بمستوى بلاتيني استثنائي",
                            Slug = "royal",
                            SortOrder = 5,
                            SupervisionPercent = 17.5m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "باقة دايموند — الخيار الأمثل لمن يريد الأفضل في كل تفصيلة، بأعلى المواصفات وأرقى الخامات.",
                            IsActive = true,
                            Name = "دايموند",
                            PricePerSqm = 9000m,
                            ShortDescription = "أعلى مستويات التشطيب والتوريدات بلا أي تنازل في الجودة",
                            Slug = "ultimate",
                            SortOrder = 6,
                            SupervisionPercent = 17.5m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PackageFeatureItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PackageSectionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PackageSectionId");

                    b.ToTable("PackageFeatureItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PackageSectionId = 1,
                            SortOrder = 1,
                            Text = "لوحة 18 خط فينوس"
                        },
                        new
                        {
                            Id = 2,
                            PackageSectionId = 1,
                            SortOrder = 2,
                            Text = "علب ماجيك وخراطيم مصطفى محمود"
                        },
                        new
                        {
                            Id = 3,
                            PackageSectionId = 1,
                            SortOrder = 3,
                            Text = "تأسيس تكيفات للشقه بالكامل ( كهرباء فقط )"
                        },
                        new
                        {
                            Id = 4,
                            PackageSectionId = 1,
                            SortOrder = 4,
                            Text = "سلك سويدى معتمد"
                        },
                        new
                        {
                            Id = 5,
                            PackageSectionId = 1,
                            SortOrder = 5,
                            Text = "لقم و مفاتيح فينوس ضمان مدى الحياه"
                        },
                        new
                        {
                            Id = 6,
                            PackageSectionId = 1,
                            SortOrder = 6,
                            Text = "عمل دائرة تليفون كاملة للشقة بالكامل"
                        },
                        new
                        {
                            Id = 7,
                            PackageSectionId = 1,
                            SortOrder = 7,
                            Text = "عمل دائرة دش كاملة للشقة بالكامل"
                        },
                        new
                        {
                            Id = 8,
                            PackageSectionId = 1,
                            SortOrder = 8,
                            Text = "تأسيس علبة للأنتركم"
                        },
                        new
                        {
                            Id = 9,
                            PackageSectionId = 1,
                            SortOrder = 9,
                            Text = "عمل برايز للشفاط جنب شبابيك المطابخ والحمامات"
                        },
                        new
                        {
                            Id = 10,
                            PackageSectionId = 1,
                            SortOrder = 10,
                            Text = "عمل مفتاح فصل للسخانات والغسالات والتكييفات"
                        },
                        new
                        {
                            Id = 11,
                            PackageSectionId = 1,
                            SortOrder = 11,
                            Text = "توريد وتركيب اسبوتات وليد للجبسوم بورد"
                        },
                        new
                        {
                            Id = 12,
                            PackageSectionId = 2,
                            SortOrder = 1,
                            Text = "توريد وتركيب خامات عزل الرطوبة للحمام مع عمل طبقة لياسة أسمنتيه لأرضية الحمام"
                        },
                        new
                        {
                            Id = 13,
                            PackageSectionId = 2,
                            SortOrder = 2,
                            Text = "تأسيس سباكة الحمام + مطبخ"
                        },
                        new
                        {
                            Id = 14,
                            PackageSectionId = 2,
                            SortOrder = 3,
                            Text = "المواسير المستخدمة فى التأسيس الشريف أو تكنو ثيرم مع اعطاء العميل شهادة ضمان"
                        },
                        new
                        {
                            Id = 15,
                            PackageSectionId = 2,
                            SortOrder = 4,
                            Text = "تشطيب السباكة قاعدة و حوض بحد اقصى 4000 جنيه للحمام الواحد – تركيب خلاطات بحد اقصي 3000 للحمام الواحد"
                        },
                        new
                        {
                            Id = 16,
                            PackageSectionId = 2,
                            SortOrder = 5,
                            Text = "تركيب بانيو للحمام أو تأسيس كابينه شاور لحمام واحد فقط بحد اقصي 4000 للحمام"
                        },
                        new
                        {
                            Id = 17,
                            PackageSectionId = 3,
                            SortOrder = 1,
                            Text = "عمل ضهارة للشقة بالكامل"
                        },
                        new
                        {
                            Id = 18,
                            PackageSectionId = 3,
                            SortOrder = 2,
                            Text = "عمل جبسوم بورد للريسيشن و الطرقه فقط"
                        },
                        new
                        {
                            Id = 19,
                            PackageSectionId = 3,
                            SortOrder = 3,
                            Text = "عمل كرانيش للغرف والطرقة"
                        },
                        new
                        {
                            Id = 20,
                            PackageSectionId = 3,
                            SortOrder = 4,
                            Text = "عمل كرانيش فيوتك للحمام والمطبخ"
                        },
                        new
                        {
                            Id = 21,
                            PackageSectionId = 4,
                            SortOrder = 1,
                            Text = "توريد وتركيب باب مصفح"
                        },
                        new
                        {
                            Id = 22,
                            PackageSectionId = 4,
                            SortOrder = 2,
                            Text = "تركيب أبواب للغرف والحمامات خشب موسكى بطبقة MDF"
                        },
                        new
                        {
                            Id = 23,
                            PackageSectionId = 4,
                            SortOrder = 3,
                            Text = "دهان الأبواب أستر أو لاكية حسب اختيار العميل"
                        },
                        new
                        {
                            Id = 24,
                            PackageSectionId = 5,
                            SortOrder = 1,
                            Text = "توريد وتركيب سيراميك للريسيبشن والطرقة (225) جنيه للمتر"
                        },
                        new
                        {
                            Id = 25,
                            PackageSectionId = 5,
                            SortOrder = 2,
                            Text = "توريد وتركيب سيراميك باقى الشقة حوائط وأرضيات ( 150 ) جنيه للمتر"
                        },
                        new
                        {
                            Id = 26,
                            PackageSectionId = 5,
                            SortOrder = 3,
                            Text = "توريد وتشوين الأسمنت والرمل ومادة السقية وكل ما يخص ذلك البند"
                        },
                        new
                        {
                            Id = 27,
                            PackageSectionId = 6,
                            SortOrder = 1,
                            Text = "وش سيلر مائى"
                        },
                        new
                        {
                            Id = 28,
                            PackageSectionId = 6,
                            SortOrder = 2,
                            Text = "عدد ( 3 ) سكينة معجون للشقة بالكامل"
                        },
                        new
                        {
                            Id = 29,
                            PackageSectionId = 6,
                            SortOrder = 3,
                            Text = "عدد ( 1 ) وش بطانة"
                        },
                        new
                        {
                            Id = 30,
                            PackageSectionId = 6,
                            SortOrder = 4,
                            Text = "عدد ( 2 ) وش تشطيب نهائى"
                        },
                        new
                        {
                            Id = 31,
                            PackageSectionId = 6,
                            SortOrder = 5,
                            Text = "الدهانات المستخدمة ماركة جي إل سي"
                        },
                        new
                        {
                            Id = 32,
                            PackageSectionId = 6,
                            SortOrder = 6,
                            Text = "عدد (1) جانب قطيفة أو ورق حائط لكل فراغ"
                        });
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PackageMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("FinishingPackageId")
                        .HasColumnType("int");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FinishingPackageId");

                    b.ToTable("PackageMedia");
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PackageNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FinishingPackageId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FinishingPackageId");

                    b.ToTable("PackageNotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FinishingPackageId = 1,
                            SortOrder = 1,
                            Text = "يتم حساب تكلفه التشطيب علي اساس المساحه الفعليه بعد المعاينه و ليس المساحه المسجله بالعقد"
                        },
                        new
                        {
                            Id = 2,
                            FinishingPackageId = 1,
                            SortOrder = 2,
                            Text = "يضاف 300 جنيه علي سعر المتر إذا كانت الشقه بدون الألوميتال"
                        },
                        new
                        {
                            Id = 3,
                            FinishingPackageId = 1,
                            SortOrder = 3,
                            Text = "يضاف 200 جنيه علي سعر المتر إذا كانت الشقه بدون محاره"
                        },
                        new
                        {
                            Id = 4,
                            FinishingPackageId = 1,
                            SortOrder = 4,
                            Text = "يضاف 100 جنيه علي سعر المترإذا رغب العميل بعمل (3D MAX )"
                        });
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PackagePaymentPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FinishingPackageId")
                        .HasColumnType("int");

                    b.Property<int>("Percentage")
                        .HasColumnType("int");

                    b.Property<string>("PhaseDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FinishingPackageId");

                    b.ToTable("PackagePaymentPhases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FinishingPackageId = 1,
                            Percentage = 35,
                            PhaseDescription = "من التكلفة عند التعاقد",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            FinishingPackageId = 1,
                            Percentage = 30,
                            PhaseDescription = "عند الانتهاء من المرحلة الاولى ( اعمال تأسيس الكهرباء – السباكة – اعمال تأسيس التكيفات)",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            FinishingPackageId = 1,
                            Percentage = 25,
                            PhaseDescription = "عند الانتهاء من المرحلة التانية ( اعمال السيراميك – اعمال الجبسمبورد)",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            FinishingPackageId = 1,
                            Percentage = 10,
                            PhaseDescription = "عند الانتهاء من المرحلة الثالثه ( اعمال الدهانات و تركيب الأبواب الداخليه + باب الشقه)",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            FinishingPackageId = 2,
                            Percentage = 35,
                            PhaseDescription = "من التكلفة عند التعاقد",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 6,
                            FinishingPackageId = 2,
                            Percentage = 30,
                            PhaseDescription = "عند الانتهاء من المرحلة الاولى",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 7,
                            FinishingPackageId = 2,
                            Percentage = 25,
                            PhaseDescription = "عند الانتهاء من المرحلة التانية",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 8,
                            FinishingPackageId = 2,
                            Percentage = 10,
                            PhaseDescription = "عند الانتهاء من المرحلة الثالثه",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 9,
                            FinishingPackageId = 3,
                            Percentage = 35,
                            PhaseDescription = "من التكلفة عند التعاقد",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 10,
                            FinishingPackageId = 3,
                            Percentage = 30,
                            PhaseDescription = "عند الانتهاء من المرحلة الاولى",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 11,
                            FinishingPackageId = 3,
                            Percentage = 25,
                            PhaseDescription = "عند الانتهاء من المرحلة التانية",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 12,
                            FinishingPackageId = 3,
                            Percentage = 10,
                            PhaseDescription = "عند الانتهاء من المرحلة الثالثه",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 13,
                            FinishingPackageId = 4,
                            Percentage = 35,
                            PhaseDescription = "من التكلفة عند التعاقد",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 14,
                            FinishingPackageId = 4,
                            Percentage = 30,
                            PhaseDescription = "عند الانتهاء من المرحلة الاولى",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 15,
                            FinishingPackageId = 4,
                            Percentage = 25,
                            PhaseDescription = "عند الانتهاء من المرحلة التانية",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 16,
                            FinishingPackageId = 4,
                            Percentage = 10,
                            PhaseDescription = "عند الانتهاء من المرحلة الثالثه",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 17,
                            FinishingPackageId = 5,
                            Percentage = 35,
                            PhaseDescription = "من التكلفة عند التعاقد",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 18,
                            FinishingPackageId = 5,
                            Percentage = 30,
                            PhaseDescription = "عند الانتهاء من المرحلة الاولى",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 19,
                            FinishingPackageId = 5,
                            Percentage = 25,
                            PhaseDescription = "عند الانتهاء من المرحلة التانية",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 20,
                            FinishingPackageId = 5,
                            Percentage = 10,
                            PhaseDescription = "عند الانتهاء من المرحلة الثالثه",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 21,
                            FinishingPackageId = 6,
                            Percentage = 35,
                            PhaseDescription = "من التكلفة عند التعاقد",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 22,
                            FinishingPackageId = 6,
                            Percentage = 30,
                            PhaseDescription = "عند الانتهاء من المرحلة الاولى",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 23,
                            FinishingPackageId = 6,
                            Percentage = 25,
                            PhaseDescription = "عند الانتهاء من المرحلة التانية",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 24,
                            FinishingPackageId = 6,
                            Percentage = 10,
                            PhaseDescription = "عند الانتهاء من المرحلة الثالثه",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PackageSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FinishingPackageId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FinishingPackageId");

                    b.ToTable("PackageSections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FinishingPackageId = 1,
                            SortOrder = 1,
                            Title = "الكهرباء"
                        },
                        new
                        {
                            Id = 2,
                            FinishingPackageId = 1,
                            SortOrder = 2,
                            Title = "بند السباكة"
                        },
                        new
                        {
                            Id = 3,
                            FinishingPackageId = 1,
                            SortOrder = 3,
                            Title = "بند الآسقف"
                        },
                        new
                        {
                            Id = 4,
                            FinishingPackageId = 1,
                            SortOrder = 4,
                            Title = "بند الآبواب"
                        },
                        new
                        {
                            Id = 5,
                            FinishingPackageId = 1,
                            SortOrder = 5,
                            Title = "بند السيراميك و الرخام"
                        },
                        new
                        {
                            Id = 6,
                            FinishingPackageId = 1,
                            SortOrder = 6,
                            Title = "بند النقاشة"
                        });
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PropertyMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PropertyUnitId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyUnitId");

                    b.ToTable("PropertyMedia");
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PropertyUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("AreaSqm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("IsPublished");

                    b.HasIndex("PropertyType");

                    b.ToTable("PropertyUnits");
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PackageFeatureItem", b =>
                {
                    b.HasOne("AqarCare.Data.Entities.PackageSection", "PackageSection")
                        .WithMany("FeatureItems")
                        .HasForeignKey("PackageSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageSection");
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PackageMedia", b =>
                {
                    b.HasOne("AqarCare.Data.Entities.FinishingPackage", "FinishingPackage")
                        .WithMany("Media")
                        .HasForeignKey("FinishingPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishingPackage");
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PackageNote", b =>
                {
                    b.HasOne("AqarCare.Data.Entities.FinishingPackage", "FinishingPackage")
                        .WithMany("Notes")
                        .HasForeignKey("FinishingPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishingPackage");
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PackagePaymentPhase", b =>
                {
                    b.HasOne("AqarCare.Data.Entities.FinishingPackage", "FinishingPackage")
                        .WithMany("PaymentPhases")
                        .HasForeignKey("FinishingPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishingPackage");
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PackageSection", b =>
                {
                    b.HasOne("AqarCare.Data.Entities.FinishingPackage", "FinishingPackage")
                        .WithMany("Sections")
                        .HasForeignKey("FinishingPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishingPackage");
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PropertyMedia", b =>
                {
                    b.HasOne("AqarCare.Data.Entities.PropertyUnit", "PropertyUnit")
                        .WithMany("Media")
                        .HasForeignKey("PropertyUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyUnit");
                });

            modelBuilder.Entity("AqarCare.Data.Entities.FinishingPackage", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Notes");

                    b.Navigation("PaymentPhases");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PackageSection", b =>
                {
                    b.Navigation("FeatureItems");
                });

            modelBuilder.Entity("AqarCare.Data.Entities.PropertyUnit", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
